services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-photon}
      POSTGRES_USER: ${POSTGRES_USER:-photon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-photon}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  app:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-photon}:${POSTGRES_PASSWORD:-photon}@db:5432/${POSTGRES_DB:-photon}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  pgdata: